const {chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH || undefined});
 const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.GAME_URL||'http://localhost:3000/');
 await page.waitForFunction(()=>document.querySelector('canvas')?.getContext('2d').getImageData(121,64,1,1).data[0]>0);await page.getByRole('button',{name:'PLAY',exact:false}).first().click();
 await page.keyboard.down('ArrowDown');await page.waitForTimeout(350);await page.keyboard.up('ArrowDown');
 await page.keyboard.down(' ');await page.waitForTimeout(700);await page.keyboard.up(' ');
 await page.screenshot({path:'output/desktop.png'});
 await page.keyboard.press('Escape');await page.getByRole('heading',{name:'PAUSED',exact:true}).waitFor();
 await page.getByRole('button',{name:'RESUME',exact:false}).first().click();
 await page.keyboard.press('r');await page.keyboard.down(' ');
 await page.getByRole('heading',{name:'GAME OVER',exact:true}).waitFor({timeout:20000});
 await page.keyboard.up(' ');await page.getByRole('button',{name:'PLAY AGAIN',exact:false}).click();
 await page.waitForTimeout(50);
 if(await page.getByRole('heading',{name:'GAME OVER',exact:true}).count())throw Error('Restart failed');
 const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:2});
 await mobile.goto(process.env.GAME_URL||'http://localhost:3000/');await mobile.waitForFunction(()=>document.querySelector('canvas')?.getContext('2d').getImageData(121,64,1,1).data[0]>0);await mobile.getByRole('button',{name:'PLAY',exact:false}).first().tap();await mobile.getByRole('heading',{name:'DEAD CENTER',exact:true}).nth(1).waitFor({state:'hidden'});
 const joystick=mobile.getByRole('group',{name:'Movement joystick'});
 await joystick.dispatchEvent('pointerdown',{pointerId:1,pointerType:'touch',clientX:105,clientY:620,bubbles:true});
 await joystick.dispatchEvent('pointerup',{pointerId:1,pointerType:'touch',bubbles:true});
 await mobile.getByRole('button',{name:'FIRE',exact:true}).tap();
 await mobile.screenshot({path:'output/mobile.png'});
 const overflow=await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(overflow)throw Error('Mobile horizontal overflow');
 if(errors.length)throw Error(errors.join('\n'));
 console.log('PASS: movement, firing, pause/resume, self-hit game over, restart, mobile controls, no overflow or browser errors');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
